# Plotting routine for the Sep 2022 Event - SolO

In [1]:
test = 'test'

In [2]:
%load_ext autoreload

%autoreload 2

import numpy as np
import matplotlib.pyplot as plt
import pickle as p

import datetime as datetime
from datetime import timedelta
import seaborn as sns
import pandas as pd
import os
#import copy as cp

import multiprocessing
import py3dcore_h4c as py3dcore_h4c

import py3dcore_h4c.fluxplot as fp

plt.switch_backend('agg')


import warnings
warnings.filterwarnings('ignore')

import logging

logging.basicConfig(level=logging.INFO)
logging.getLogger("heliosat.spice").setLevel("WARNING")
logging.getLogger("heliosat.spacecraft").setLevel("WARNING")
#logging.getLogger("sunpy").setLevel("WARNING")
#logging.getLogger("py3dcore_h4c.fluxplot").setLevel("WARNING")

#print(sns.__version__)

#### setting the times for py3DCORE_h4c

In [3]:
t_launch = datetime.datetime(2022, 9, 5, 18, tzinfo=datetime.timezone.utc) # launch time assumed at CME impact at PSP at 14.72 Rs

t_s = datetime.datetime(2022, 9, 7, 8, tzinfo=datetime.timezone.utc) 
t_e = datetime.datetime(2022, 9, 8, 3, tzinfo=datetime.timezone.utc)

t_fit = [
        datetime.datetime(2022, 9, 7, 9, tzinfo=datetime.timezone.utc),
        datetime.datetime(2022, 9, 7, 15, tzinfo=datetime.timezone.utc),
        datetime.datetime(2022, 9, 7, 20, tzinfo=datetime.timezone.utc),
        datetime.datetime(2022, 9, 8, 2, tzinfo=datetime.timezone.utc)
     ]



In [4]:
fittingPoints = []

fittingPoints = [t_fit[i].strftime("%m/%d/%Y, %H:%M:%S") for i in range(len(t_fit))]
print(fittingPoints)

['09/07/2022, 09:00:00', '09/07/2022, 15:00:00', '09/07/2022, 20:00:00', '09/08/2022, 02:00:00']


#### loading the pickle files

In [5]:
path = 'output/HTR_sep2022_multi_1024_1/'

filepath = fp.loadpickle(path, number=-1)

In [6]:
filepath[:-7]

'output/HTR_sep2022_multi_1024_1/04'

#### extracting parameters

In [7]:
res, allres, ind, meanparams = fp.get_params(filepath, give_mineps=True)

INFO:py3dcore_h4c.fluxplot:Retrieved the following parameters for the run with minimum epsilon:
INFO:py3dcore_h4c.fluxplot: --lon:  107.19
INFO:py3dcore_h4c.fluxplot: --lat:  -8.92
INFO:py3dcore_h4c.fluxplot: --inc:  147.35
INFO:py3dcore_h4c.fluxplot: --diameter 1 AU:  0.37
INFO:py3dcore_h4c.fluxplot: --aspect ratio:  3.40
INFO:py3dcore_h4c.fluxplot: --launch radius:  7.46
INFO:py3dcore_h4c.fluxplot: --launch speed:  977.63
INFO:py3dcore_h4c.fluxplot: --t factor:  -187.22
INFO:py3dcore_h4c.fluxplot: --expansion rate:  1.14
INFO:py3dcore_h4c.fluxplot: --magnetic field decay rate:  1.64
INFO:py3dcore_h4c.fluxplot: --magnetic field 1 AU:  5.33
INFO:py3dcore_h4c.fluxplot: --drag coefficient:  0.60
INFO:py3dcore_h4c.fluxplot: --sw background speed:  665.86


In [8]:
out = fp.get_ensemble_stats(filepath)

In [9]:
out.describe()

lon         lat         inc        D1AU       delta  \
count  512.000000  512.000000  512.000000  512.000000  512.000000   
mean   114.573196   -1.002198  147.973724    0.369591    2.738959   
std      9.046782   15.745078   11.479082    0.065245    1.188832   
min    100.162102  -40.151085  115.775215    0.253623    1.012336   
25%    108.104235  -11.582997  140.186848    0.320584    1.800441   
50%    112.996590   -1.297401  147.781433    0.359650    2.528248   
75%    119.193710    9.784729  156.369633    0.404907    3.333768   
max    155.764801   47.842178  179.417053    0.621962    6.824233   

       launch radius  launch speed    t factor        B1AU       gamma  \
count     512.000000    512.000000  512.000000  512.000000  512.000000   
mean       10.662553   1158.717041 -161.578796    6.614710    2.139937   
std         2.946345    439.462402   51.934349    1.714799    0.971253   
min         5.011993    102.307747 -249.829559    5.005971    0.258380   
25%         8.461927    837.829285 -204.085030    5.584728    1.346614   
50%        10.793511   1163.955872 -165.182320    6.137742    2.159695   
75%        12.980604   1500.678345 -123.509623    7.089155    2.901197   
max        15.976678   1998.760376  -13.608272   16.837881    3.971911   

              vsw  
count  512.000000  
mean   761.137329  
std     90.613945  
min    400.483429  
25%    696.412704  
50%    776.026581  
75%    830.947464  
max    899.858948

#### loading and plotting the fitting results

In [10]:
t_s = datetime.datetime(2022, 9, 7, 5, tzinfo=datetime.timezone.utc) 
t_e = datetime.datetime(2022, 9, 8, 8, tzinfo=datetime.timezone.utc)

In [17]:
fp.fullinsitu(observer='SOLO', t_fit=t_fit, start=t_s, end=t_e, filepath=filepath, custom_data='solo_2022sep.p', best=True, ensemble=True, 
              mean=False, save_fig=True, legend=True, fixed=None, max_index=512, title=True, fit_points=True)

INFO:py3dcore_h4c.fluxplot:No iparams_arr given, using parameters for run with minimum eps.


[[ 0.00000000e+00  1.07192856e+02 -8.92177391e+00  1.47352005e+02
   3.74855191e-01  3.39798403e+00  7.45784521e+00  9.77631042e+02
  -1.87217300e+02  1.13999999e+00  1.63999999e+00  5.32873678e+00
   6.03684187e-01  6.65863586e+02]]


INFO:py3dcore_h4c.fitter.base:Using custom datafile: solo_2022sep.p


[datetime.datetime(2022, 9, 7, 5, 0, tzinfo=datetime.timezone.utc)
 datetime.datetime(2022, 9, 7, 5, 1, 0, 37060, tzinfo=datetime.timezone.utc)
 datetime.datetime(2022, 9, 7, 5, 2, 0, 74120, tzinfo=datetime.timezone.utc)
 ...
 datetime.datetime(2022, 9, 8, 7, 57, 59, 925880, tzinfo=datetime.timezone.utc)
 datetime.datetime(2022, 9, 8, 7, 58, 59, 962940, tzinfo=datetime.timezone.utc)
 datetime.datetime(2022, 9, 8, 8, 0, tzinfo=datetime.timezone.utc)] [[-0.59367231  0.34327763 -0.0453283 ]
 [-0.59366779  0.34327107 -0.04532952]
 [-0.59366326  0.34326452 -0.04533075]
 ...
 [-0.5863217   0.33240801 -0.04728521]
 [-0.58631713  0.33240112 -0.04728641]
 [-0.586308    0.33238733 -0.04728879]] [[nan nan nan]
 [nan nan nan]
 [nan nan nan]
 ...
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]]


In [12]:
fp.scatterparams(filepath)

In [13]:
print(out['lon'].mean())
print(out['lon'].std())
print(out['launch radius'].std())
print(out['launch speed'].std())

114.5732
9.0467825
2.9463453
439.4624


#### Plotting the fluxrope and spacecraft positions

In [14]:
#measurement times 
#tm0 =  t_launch + datetime.timedelta(days=1.5)
tm0 =  datetime.datetime(2022, 9, 5, 16)
tm1 =  t_launch + datetime.timedelta(days=1.7)
tm2 =  t_launch + datetime.timedelta(days=3.5)

fig = fp.full3d(spacecraftlist=['solo', 'psp'], planetlist=['Earth'], t=tm1, filepath=filepath)

INFO:py3dcore_h4c.fluxplot:Plotting run with mean parameters.


[[ 0.0000000e+00  1.1457316e+02 -1.0021974e+00  1.4797371e+02
   3.6959118e-01  2.7389586e+00  1.0662551e+01  1.1587168e+03
  -1.6157874e+02  1.1400080e+00  1.6400100e+00  6.6147141e+00
   2.1399360e+00  7.6113745e+02]]


INFO:sunpy:Obtained JPL HORIZONS location for Solar Orbiter (spacecraft) (-144


INFO: Obtained JPL HORIZONS location for Solar Orbiter (spacecraft) (-144 [sunpy.coordinates.ephemeris]


INFO:py3dcore_h4c.fluxplot:Indices of date: 3479
INFO:py3dcore_h4c.fluxplot:Solar Orbiter - r: 0.684921, lon: 150.054373, lat: -3.723044, 
INFO:sunpy:Obtained JPL HORIZONS location for Solar Orbiter (spacecraft) (-144


INFO: Obtained JPL HORIZONS location for Solar Orbiter (spacecraft) (-144 [sunpy.coordinates.ephemeris]


INFO:py3dcore_h4c.fluxplot:Indices of date: 2039
INFO:py3dcore_h4c.fluxplot:Solar Orbiter - r: 0.684921, lon: 150.054373, lat: -3.723044, 
INFO:sunpy:Obtained JPL HORIZONS location for Parker Solar Probe (spacecraft)


INFO: Obtained JPL HORIZONS location for Parker Solar Probe (spacecraft) [sunpy.coordinates.ephemeris]


INFO:py3dcore_h4c.fluxplot:Indices of date: 3479
INFO:py3dcore_h4c.fluxplot:Parker Solar Probe - r: 0.093683, lon: -123.690639, lat: -2.188183, 
INFO:sunpy:Obtained JPL HORIZONS location for Parker Solar Probe (spacecraft)


INFO: Obtained JPL HORIZONS location for Parker Solar Probe (spacecraft) [sunpy.coordinates.ephemeris]


INFO:py3dcore_h4c.fluxplot:Indices of date: 2039
INFO:py3dcore_h4c.fluxplot:Parker Solar Probe - r: 0.093683, lon: -123.690639, lat: -2.188183, 


### make fluxrope 3d movie

In [15]:
def make_frame(k):
    tm0 = datetime.datetime(2022, 9, 5, 19)
    t = tm0 + k*datetime.timedelta(hours=1)
    
    fig = fp.full3d(spacecraftlist=['solo', 'psp'], planetlist =['Earth'],
              t = t, filepath = filepath, save_fig = False)
    frmstr = '%05i' % (k) 
    plt.savefig(filepath[:-7] + 'movie_3d/'+frmstr+'.jpg',dpi=200)  
    return fig
    

In [16]:
inn=[i for i in range(100)]


mpool = multiprocessing.Pool(processes=5)
mpool.map(make_frame, inn[0:20])
mpool.close()
mpool.join()

print('done 1/4')

mpool = multiprocessing.Pool(processes=5)
mpool.map(make_frame, inn[20:40])
mpool.close()
mpool.join()

print('done 2/4')

mpool = multiprocessing.Pool(processes=5)
mpool.map(make_frame, inn[40:60])
mpool.close()
mpool.join()

print('done 3/4')

mpool = multiprocessing.Pool(processes=5)
mpool.map(make_frame, inn[40:80])
mpool.close()
mpool.join()

print('done 4/4')

Process SpawnPoolWorker-4:
Process SpawnPoolWorker-3:
Process SpawnPoolWorker-2:
Process SpawnPoolWorker-1:
Process SpawnPoolWorker-5:
Traceback (most recent call last):
  File "/Users/hannahruedisser/miniforge3/envs/3dcorenv/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/hannahruedisser/miniforge3/envs/3dcorenv/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/hannahruedisser/miniforge3/envs/3dcorenv/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/hannahruedisser/miniforge3/envs/3dcorenv/lib/python3.10/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
Traceback (most recent call last):
AttributeError: Can't get attribute 'make_frame' on <module '__main__' (built-in)>
  File "/Users/hannahruedisser/miniforge3/envs/3dcorenv/lib/python3.10/multiprocessing/process.py", line 314, in _bootstra

In [ ]:
os.system('ffmpeg -r 25 -i '+filepath[:-7]+'movie_3d/%05d.jpg -b 5000k -r 25 '+filepath[:-7]+'movie_3d/full_3d_movie.mp4 -y -loglevel quiet')

dule>
    import bz2
  File "/Users/hannahruedisser/miniforge3/envs/3dcorenv/lib/python3.10/bz2.py", line 17, in <module>
    addsitedir(sitedir, known_paths)
  File "/Users/hannahruedisser/miniforge3/envs/3dcorenv/lib/python3.10/site.py", line 226, in addsitedir
    from _bz2 import BZ2Compressor, BZ2Decompressor
KeyboardInterrupt
    addpackage(sitedir, name, known_paths)
  File "/Users/hannahruedisser/miniforge3/envs/3dcorenv/lib/python3.10/site.py", line 186, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 975, in get_code
  File "<frozen importlib._bootstrap_external>", line 1074, in get_data
KeyboardInterrupt
Process SpawnP

### plot fluxrope 3d multiview

In [ ]:
#measurement times 
#tm0 =  t_launch + datetime.timedelta(days=1.5)
tm0 =  datetime.datetime(2022, 9, 7, 1)
tm1 =  t_launch + datetime.timedelta(days=1.7)
tm2 =  t_launch + datetime.timedelta(days=3.5)

fig = fp.full3d_multiview(t_launch = t_launch, filepath=filepath)

oolWorker-28:
Traceback (most recent call last):
  File "/Users/hannahruedisser/miniforge3/envs/3dcorenv/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/hannahruedisser/miniforge3/envs/3dcorenv/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/hannahruedisser/miniforge3/envs/3dcorenv/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/hannahruedisser/miniforge3/envs/3dcorenv/lib/python3.10/multiprocessing/queues.py", line 365, in get
    res = self._reader.recv_bytes()
  File "/Users/hannahruedisser/miniforge3/envs/3dcorenv/lib/python3.10/multiprocessing/connection.py", line 221, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/Users/hannahruedisser/miniforge3/envs/3dcorenv/lib/python3.10/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/Users/hannahruedisser/miniforge3/envs

### make fluxrope 3d multiview movie

In [ ]:
def make_frame2(k):
    tm0 = datetime.datetime(2022, 9, 5, 19)
    t = tm0 + k*datetime.timedelta(hours=1)
    frametime = k
    
    fig = fp.full3d_multiview_movie(t_launch = tm0, t = t, filepath=filepath,
                                    frametime=k)
    frmstr = '%05i' % (k) 
    plt.savefig(filepath[:-7] + 'movie_3d_multiview/'+frmstr+'.jpg',dpi=200)  
    return fig

In [ ]:
inn=[i for i in range(100)]


mpool = multiprocessing.Pool(processes=5)
mpool.map(make_frame2, inn[0:20])
mpool.close()
mpool.join()

print('done 1/4')

mpool = multiprocessing.Pool(processes=5)
mpool.map(make_frame2, inn[20:40])
mpool.close()
mpool.join()

print('done 2/4')

mpool = multiprocessing.Pool(processes=5)
mpool.map(make_frame2, inn[40:60])
mpool.close()
mpool.join()

print('done 3/4')

mpool = multiprocessing.Pool(processes=5)
mpool.map(make_frame2, inn[40:80])
mpool.close()
mpool.join()

print('done 4/4')

In [ ]:
os.system('ffmpeg -r 25 -i '+filepath[:-7]+'movie_3d_multiview/%05d.jpg -b 5000k -r 25 '+filepath[:-7]+'movie_3d/full_3d_multiview_movie.mp4 -y -loglevel quiet')

# Used for Debug

In [ ]:
TP_A =  t_launch + datetime.timedelta(hours=2)
TP_B =  t_launch + datetime.timedelta(hours=40)


C_A = "xkcd:red"
C_B = "xkcd:blue"
    
sns.set_style('whitegrid')

fig = plt.figure(figsize=(15, 11),dpi=100)

ax1 = plt.subplot2grid((2, 3), (0, 0),rowspan=2,colspan=2,projection='3d')  
ax2 = plt.subplot2grid((2, 3), (0, 2),projection='3d')  
ax3 = plt.subplot2grid((2, 3), (1, 2),projection='3d')  

model_obj = fp.returnmodel(filepath)


fp.plot_configure(ax1, view_azim=150, view_elev=25, view_radius=.2,light_source=True) #view_radius=.08

fp.plot_3dcore(ax1, model_obj, TP_A, color=C_A,light_source = True)
fp.plot_3dcore(ax1, model_obj, TP_B, color=C_B,light_source = True)

fp.plot_shift(ax1,0.31,-0.25,0.0,-0.2)


fp.plot_configure(ax2, view_azim=165-90, view_elev=90, view_radius=.08,light_source=True)
    
fp.plot_3dcore(ax2, model_obj, TP_A, color=C_A,light_source = True)
fp.plot_3dcore(ax2, model_obj, TP_B, color=C_B,light_source = True)

fp.plot_shift(ax2,0.26,-0.41,0.08,0.0)



fp.plot_configure(ax3, view_azim=65, view_elev=-5, view_radius=.01,light_source=True)
    
fp.plot_3dcore(ax3, model_obj, TP_A, color=C_A,light_source = True)
fp.plot_3dcore(ax3, model_obj, TP_B, color=C_B,light_source = True)

fp.plot_shift(ax3,0.26,-0.41,0.08,0.0)

